// blockshell-engine.js
// Core BlockShell engine for Blockly + PowerShell

export class BlockShellEngine {
  constructor() {
    this.workspace = null;
    this.generators = {};       // type -> generator fn
    this.blockMeta = {};        // type -> { message, tooltip }
    this.originalToolboxDom = null;
    this.currentModule = 'core';
  }

  init({ blocklyDivId, toolboxId }) {
    const toolboxEl = document.getElementById(toolboxId);
    if (!toolboxEl) {
      console.error('Toolbox element not found:', toolboxId);
      return;
    }

    // Cache original toolbox DOM for filtering
    this.originalToolboxDom = toolboxEl.cloneNode(true);

    this.workspace = Blockly.inject(blocklyDivId, {
      toolbox: toolboxEl,
      scrollbars: true,
      trashcan: true,
      grid: {
        spacing: 25,
        length: 3,
        colour: '#e0e0e0',
        snap: true
      },
      zoom: {
        controls: false,
        wheel: true,
        startScale: 1.0,
        maxScale: 3,
        minScale: 0.3,
        scaleSpeed: 1.2
      },
      theme: Blockly.Themes.Classic
    });

    // Zoom buttons
    const zoomInBtn = document.getElementById('zoom-in');
    const zoomOutBtn = document.getElementById('zoom-out');
    const resetZoomBtn = document.getElementById('reset-zoom-btn');

    if (zoomInBtn) zoomInBtn.addEventListener('click', () => this.workspace.zoomCenter(1.2));
    if (zoomOutBtn) zoomOutBtn.addEventListener('click', () => this.workspace.zoomCenter(0.8));
    if (resetZoomBtn) resetZoomBtn.addEventListener('click', () => {
      this.workspace.setScale(1.0);
      this.workspace.scrollCenter();
    });

    // Clear + Show Script
    const clearBtn = document.getElementById('clear-workspace-btn');
    const showScriptBtn = document.getElementById('show-script-btn');

    if (clearBtn) clearBtn.addEventListener('click', () => this.clearWorkspace());
    if (showScriptBtn) showScriptBtn.addEventListener('click', () => this.showScriptModal());
  }

  registerBlocks(blockJsonArray, generatorMap) {
    if (Array.isArray(blockJsonArray) && blockJsonArray.length) {
      Blockly.defineBlocksWithJsonArray(blockJsonArray);
      for (const b of blockJsonArray) {
        this.blockMeta[b.type] = {
          message: b.message0 || '',
          tooltip: b.tooltip || ''
        };
      }
    }
    if (generatorMap && typeof generatorMap === 'object') {
      Object.assign(this.generators, generatorMap);
    }
  }

  setModule(moduleId) {
    this.currentModule = moduleId;
  }

  filterToolbox(query) {
    if (!this.workspace || !this.originalToolboxDom) return;

    const q = (query || '').trim().toLowerCase();

    // No search text → reset toolbox
    if (!q) {
      const xmlText = Blockly.utils.xml.domToText(this.originalToolboxDom);
      this.workspace.updateToolbox(xmlText);
      return;
    }

    const filteredDom = this.originalToolboxDom.cloneNode(true);

    const blocks = filteredDom.getElementsByTagName('block');
    for (let i = blocks.length - 1; i >= 0; i--) {
      const blk = blocks[i];
      const type = blk.getAttribute('type') || '';
      const meta = this.blockMeta[type] || {};
      const haystack = [
        type,
        meta.message || '',
        meta.tooltip || ''
      ].join(' ').toLowerCase();

      if (!haystack.includes(q)) {
        blk.parentNode.removeChild(blk);
      }
    }

    // Remove categories with no blocks
    const cats = filteredDom.getElementsByTagName('category');
    for (let i = cats.length - 1; i >= 0; i--) {
      if (!cats[i].getElementsByTagName('block').length) {
        cats[i].parentNode.removeChild(cats[i]);
      }
    }

    const filteredText = Blockly.utils.xml.domToText(filteredDom);
    this.workspace.updateToolbox(filteredText);
  }

  clearWorkspace() {
    if (!this.workspace) return;
    this.workspace.clear();
    this.showNotification('Workspace cleared');
  }

  generatePowerShellCode() {
    if (!this.workspace) return '';

    const blocks = this.workspace.getTopBlocks(true);
    let code = '';

    code += `# Generated by BlockShell Lite (PowerShell)\n`;
    code += `# Module: ${this.currentModule}\n`;
    code += `# Date: ${new Date().toISOString()}\n\n`;

    for (const block of blocks) {
      code += this._generateBlockCodeRecursive(block);
    }

    return code.trim();
  }

  _generateBlockCodeRecursive(block) {
    if (!block) return '';
    let code = '';
    const gen = this.generators[block.type];
    if (typeof gen === 'function') {
      code += gen(block) || '';
    }
    const next = block.getNextBlock();
    if (next) {
      code += this._generateBlockCodeRecursive(next);
    }
    return code;
  }

  createModal(title) {
    const modal = document.createElement('div');
    modal.className = 'modal';

    const content = document.createElement('div');
    content.className = 'modal-content';

    const header = document.createElement('div');
    header.className = 'modal-header';

    const titleEl = document.createElement('h3');
    titleEl.className = 'modal-title';
    titleEl.textContent = title;

    const closeBtn = document.createElement('button');
    closeBtn.className = 'close-btn';
    closeBtn.innerHTML = '&times;';
    closeBtn.onclick = () => {
      document.body.removeChild(modal);
    };

    header.appendChild(titleEl);
    header.appendChild(closeBtn);
    content.appendChild(header);
    modal.appendChild(content);
    return modal;
  }

  showScriptModal() {
    const code = this.generatePowerShellCode();
    if (!code) {
      this.showNotification('No script to show. Add some blocks first.');
      return;
    }

    const modal = this.createModal('Generated PowerShell Script');

    const codeBlock = document.createElement('div');
    codeBlock.className = 'code-block';

    const pre = document.createElement('pre');
    pre.textContent = code;
    if (window.hljs) {
      hljs.highlightElement(pre);
    }

    codeBlock.appendChild(pre);

    const copyBtn = document.createElement('button');
    copyBtn.textContent = 'Copy to Clipboard';
    copyBtn.className = 'ghost';
    copyBtn.style.marginTop = '8px';
    copyBtn.onclick = () => {
      navigator.clipboard.writeText(code).then(() => {
        this.showNotification('Script copied to clipboard');
      });
    };

    const content = modal.querySelector('.modal-content');
    content.appendChild(codeBlock);
    content.appendChild(copyBtn);

    document.body.appendChild(modal);
  }

  showNotification(message) {
    const n = document.createElement('div');
    n.className = 'notification';
    n.textContent = message;
    document.body.appendChild(n);

    requestAnimationFrame(() => {
      n.classList.add('show');
    });

    setTimeout(() => {
      n.classList.remove('show');
      setTimeout(() => {
        if (n.parentNode) n.parentNode.removeChild(n);
      }, 300);
    }, 2500);
  }
}
