name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_SAND_0ECE8C703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Deploy the static site that lives under courses/firstline
          app_location: "courses/firstline"
          api_location: ""
          # No build step; deploy files directly from app_location
          output_location: ""
          # Ensure production points at your default branch
          production_branch: "master"

